#!/bin/sh
#PBS -N CONCOCT
#PBS -q fluxod
#PBS -l qos=flux
#PBS -l nodes=1:ppn=8,mem=32GB
#PBS -l walltime=300:00:00
#PBS -j oe
#PBS -V
#PBS -M mljenior@umich.edu
#PBS -A pschloss_fluxod

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID
cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`


for x in *.genes.pep.80.fasta
do 
cluster="${x//.genes.pep.80.fasta}"

# Diamond BLAST against KEGG peptide database
/nfs/turbo/pschloss/bin/diamond blastp -p 8 -d /nfs/turbo/pschloss/kegg/kegg/genes/fasta/kegg_prot_dmnd_db -q ${cluster}.genes.pep.80.fasta -a ${cluster}.annotated --max-target-seqs 1
/nfs/turbo/pschloss/bin/diamond view -a ${cluster}.annotated.daa -f tab -o ${cluster}.protVprot.out

# Add best BLASTp hits to corresponding nucleotide fasta file entry
python /nfs/turbo/pschloss/matt/home/scripts/annotate_fasta.py ${cluster}.protVprot.out ${cluster}.genes.nuc.250.fasta

# Dereplicate annotated nucleotide fasta
/nfs/turbo/pschloss/bin/cdhit/cd-hit-est -i ${cluster}.genes.nuc.250.annotated.fasta -o ${cluster}.genes.nuc.250.annotated.unique.fasta -c 1.0 -n 11 -M 44000 -T 8

# Create Bowtie 2 database for the new fasta file
/nfs/turbo/pschloss/bin/bowtie2-build ${cluster}.genes.nuc.250.annotated.unique.fasta ${cluster}_gene_db
done


echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit
