#!/bin/sh
#PBS -l nodes=1:ppn=1
#PBS -l walltime=300:00:00
#PBS -l mem=10gb
#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -M mljenior@umich.edu
#PBS -q first
#PBS -A schloss_lab

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`


cp /mnt/EXT/Schloss-data/matt/metagenomes_HiSeq/${metagenome}/annotation/${metagenome}.genes.250.format.unique.annotated.fna ./
/mnt/EXT/Schloss-data/bin/bowtie2-build ${metagenome}.genes.250.format.unique.annotated.fna ${metagenome}_metaG_db
rm ${metagenome}.genes.250.format.unique.annotated.fna


echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit