#!/bin/sh
#PBS -N metaG_DNA_mapping
#PBS -q fluxod
#PBS -l qos=flux
#PBS -l nodes=1:ppn=4,mem=32GB
#PBS -l walltime=300:00:00
#PBS -j oe
#PBS -V
#PBS -M mljenior@umich.edu
#PBS -A pschloss_fluxod

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`


# Align paired-end reads to respective metagenome
/nfs/turbo/pschloss/bin/bowtie2 -f --fr -p 8 -x /nfs/turbo/pschloss/matt/metagenomes_HiSeq/gene_dbs/${metagenomeDB}_metaG_db \
        -1 /nfs/turbo/pschloss/matt/metagenomes_HiSeq/curation/${metagenome}/${metagenome}.read1.pool.cut.trim.fasta \
        -2 /nfs/turbo/pschloss/matt/metagenomes_HiSeq/curation/${metagenome}/${metagenome}.read2.pool.cut.trim.fasta \
        -S ${metagenome}.${metagenomeDB}.metaG.pair.sam
samtools view -bS ${metagenome}.${metagenomeDB}.metaG.pair.sam > ${metagenome}.${metagenomeDB}.metaG.pair.bam
samtools sort ${metagenome}.${metagenomeDB}.metaG.pair.bam ${metagenome}.${metagenomeDB}.metaG.pair.sort
rm ${metagenome}.${metagenomeDB}.metaG.pair.sam

# Align orphaned reads to respective metagenome
/nfs/turbo/pschloss/bin/bowtie2 -f -p 8 -x /nfs/turbo/pschloss/matt/metagenomes_HiSeq/gene_dbs/${metagenomeDB}_metaG_db \
        -U /nfs/turbo/pschloss/matt/metagenomes_HiSeq/curation/${metagenome}/${metagenome}.pool.cut.trim.orphan.fasta \
        -S ${metagenome}.${metagenomeDB}.metaG.orphan.sam
samtools view -bS ${metagenome}.${metagenomeDB}.metaG.orphan.sam > ${metagenome}.${metagenomeDB}.metaG.orphan.bam
samtools sort ${metagenome}.${metagenomeDB}.metaG.orphan.bam ${metagenome}.${metagenomeDB}.metaG.orphan.sort
rm ${metagenome}.${metagenomeDB}.metaG.orphan.sam

# Merge alignments and convert to idxstats format
samtools merge ${metagenome}.${metagenomeDB}.metaG.merge.bam ${metagenome}.${metagenomeDB}.metaG.pair.sort.bam ${metagenome}.${metagenomeDB}.metaG.orphan.sort.bam
samtools sort ${metagenome}.${metagenomeDB}.metaG.merge.bam ${metagenome}.${metagenomeDB}.metaG.merge.sort

# Remove PCR duplicates and sort
java -Xmx2g -jar /nfs/turbo/pschloss/matt/bin/picard-tools-1.119/MarkDuplicates.jar \
        INPUT=${metagenome}.${metagenomeDB}.metaG.merge.sort.bam \
        OUTPUT=${metagenome}.${metagenomeDB}.metaG.merge.sort.rmdup.bam \
        METRICS_FILE=${metagenome}.${metagenomeDB}.metaG.merge.sort.rmdup.metrics \
        AS=TRUE \
        VALIDATION_STRINGENCY=LENIENT \
        MAX_FILE_HANDLES_FOR_READ_ENDS_MAP=1000 \
        REMOVE_DUPLICATES=TRUE
samtools sort ${metagenome}.${metagenomeDB}.metaG.merge.sort.rmdup.bam ${metagenome}.${metagenomeDB}.metaG.merge.sort.rmdup.sort
samtools index ${metagenome}.${metagenomeDB}.metaG.merge.sort.rmdup.sort.bam

# Convert to human-readable format
samtools idxstats ${metagenome}.${metagenomeDB}.metaG.merge.sort.rmdup.sort.bam > ${metagenome}.${metagenomeDB}.metaG.final.txt

# Format and normalize idxstats files
python /nfs/turbo/pschloss/matt/home/scripts/idxstats/pool_unmapped_idxstats.py ${metagenome}.${metagenomeDB}.metaG.final.txt
python /nfs/turbo/pschloss/matt/home/scripts/idxstats/normalize_idxstats.py ${metagenome}.${metagenomeDB}.metaG.final.pool.txt 50


echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit
