#!/bin/sh
#PBS -N pooling_RNA
#PBS -l nodes=1:ppn=2
#PBS -l walltime=500:00:00
#PBS -l mem=25gb
#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -M mljenior@umich.edu
#PBS -q first
#PBS -A schloss_lab

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`


# Unzip and pool reads by lane
zcat *_L00*_R1_*.fastq.gz > ${transcriptome}.read1.pool.fastq.gz
zcat *_L00*_R2_*.fastq.gz > ${transcriptome}.read2.pool.fastq.gz
gunzip ${transcriptome}*.pool.fastq.gz

# Return some stats on the pooled fastqs
python /mnt/EXT/Schloss-data/bin/seq_stats.py ${transcriptome}.read1.pool.fastq > ${transcriptome}.pooling.summary
python /mnt/EXT/Schloss-data/bin/seq_stats.py ${transcriptome}.read2.pool.fastq >> ${transcriptome}.pooling.summary


echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit
