#!/bin/sh
#PBS -N preCONCOCT
#PBS -q fluxod
#PBS -l qos=flux
#PBS -l nodes=1:ppn=4,mem=32GB
#PBS -l walltime=200:00:00
#PBS -j oe
#PBS -V
#PBS -M mljenior@umich.edu
#PBS -A pschloss_fluxod


# Load modules
module load samtools
module load python-anaconda2/latest
module load concoct/0.4.0





# Might need to navigate to assembly directory and get contigs




# Format contigs for optimal mapping as CONCOCT input
python /nfs/turbo/schloss-lab/mljenior/home/scripts/removeShortSeqs.py ${metagenome}.final.contigs.fa 1000 > ${metagenome}.final.contigs.1k.fa
python /share/apps/rhel6/concoct/0.4.0/scripts/cut_up_fasta.py -c 10000 -o 0 -m ${metagenome}.final.contigs.1k.fa > ${metagenome}.final.contigs.1k.10k.fa
rm ${metagenome}.final.contigs.fa ${metagenome}.final.contigs.1k.fa

# Create a bowite database
/nfs/turbo/schloss-lab/bin/bowtie2-build -f ${metagenome}.final.contigs.1k.10k.fa ${metagenome}.contig_db

# Align paired-end reads to contigs
/nfs/turbo/schloss-lab/bin/bowtie2 -f --fr -x ${metagenome}.contig_db -1 ${metagenome}.read1.pool.cut.trim.mus_filtered.fasta -2 ${metagenome}.read2.pool.cut.trim.mus_filtered.fasta -S ${metagenome}.reads2contigs.sam
samtools faidx ${metagenome}.final.contigs.1k.10k.fa
samtools view -bt ${metagenome}.final.contigs.1k.10k.fa.fai ${metagenome}.reads2contigs.sam > ${metagenome}.reads2contigs.bam
rm ${metagenome}.reads2contigs.sam
samtools sort ${metagenome}.reads2contigs.bam ${metagenome}.reads2contigs.sorted
samtools index ${metagenome}.reads2contigs.sorted.bam

# Get coverage using BEDtools
/nfs/turbo/schloss-lab/mljenior/bin/bedtools2/bin/genomeCoverageBed -ibam ${metagenome}.reads2contigs.sorted.bam -g ${metagenome}.final.contigs.1k.10k.fa > ${metagenome}.coverage.txt

# Create coverage table
python /nfs/turbo/schloss-lab/bin/CONCOCT-0.3.2/scripts/gen_input_table.py --isbedfiles ${metagenome}.final.contigs.1k.10k.fa  ${metagenome}.coverage.txt > ${metagenome}.coveragetable.tsv

# Create linkage table
python /nfs/turbo/schloss-lab/bin/CONCOCT-0.3.2/scripts/bam_to_linkage.py -m 8 --regionlength 500 --fullsearch ${metagenome}.final.contigs.1k.10k.fa ${metagenome}.reads2contigs.sorted.bam > ${metagenome}.linkagetable.tsv


echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit
